from blog.api.serializers import PostSerializer
posts = Post.objects.all()
return JsonResponse({"data": PostSerializer(posts, many=True).data})
serializer = PostSerializer(data=post_data)
serializer.is_valid(raise_exception=True)
post = serializer.save()
return JsonResponse(PostSerializer(post).data)
serializer = PostSerializer(post, data=post_data)
serializer.is_valid(raise_exception=True)
serializer.save()
